import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Aside from "@/components/layout/aside";
import Header from "@/components/layout/header";
import TopBar from "@/components/navigation/topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-orange-300 ${inter.className}`}
      >
        {/*<div className="sticky top-0 flex flex-row">
          <Header className="flex flex-grow" />
          <nav>Categories</nav>
        </div>*/}
        <TopBar/>
        <div className="flex flex-1 flex-col overflow-y-hidden md:flex-row">
          {/*<Aside className="order-first sm:w-32" />*/}
          <main className="flex-1 overflow-y-auto bg-indigo-100">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
