import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Aside from "@/components/layout/aside";
import Header from "@/components/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} grid grid-cols-1 overflow-hidden md:grid-cols-12`}
      >
        <Header className="md:col-span-full " />

        <Aside className="overflow-auto md:col-span-2 md:max-h-screen md:overflow-y-auto" />
        <main className="overflow-auto  md:col-span-10 md:grid-flow-col">
          {children}
        </main>
      </body>
    </html>
  );
}
