import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Aside from "@/components/layout/aside";
import Header from "@/components/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="size-">
      <body className={`${inter.className} size-full overflow-auto`}>
        <div className="md:block max-h-max">
          <Header />
          <Aside />
          <main className="h-full flex overflow-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
